### ISSUE TITLE
git expander

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/expand-pkg#1]
The `git` expander is merging all of the properties from parsing the `repository` onto the config. This is overwriting `config.name` so when a scoped name is used that might be different than the repo name, it gets overwritten.

I updated this locally to use [defaults-deep](https://github.com/jonschlinkert/defaults-deep) instead of `merge` and it solves that issue (I don't know if it introduces any others).

If this seems like the correct change, I'll submit a PR with tests when I have a chance.

**Comment by jonschlinkert** [comment]
Can you try symlinking it to something like verb-generate-readme, and do a diff of the context?

**Comment by doowb** [comment]
I did `console.log(JSON.stringify(app.cache.data, null, 2));` in `verb-generate-readme` after `verb-repo-data` is registered and saved the output in `merge.json` and `defaults.json`.

This is the results of running `diff merge.json defaults.json`:

```diff
10,12c10,12
<     "alias": "doowb",
<     "varname": "doowb",
<     "name": "doowb",
---
>     "alias": "@doowb/foo",
>     "varname": "doowbFoo",
>     "name": "@doowb/foo",
18c18
<   "name": "doowb",
---
>   "name": "@doowb/foo",
65c65
<   "varname": "doowb",
---
>   "varname": "doowbFoo",
96c96
<   "alias": "doowb",
---
>   "alias": "@doowb/foo",
```

It looks like the only changes are related to the `name` which is what I was hoping.
